name: ticket_collection
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  intl: ^0.20.2
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  printing: ^5.14.2
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80